// Ordered map — longer/more specific phrases must come before shorter ones
export const COMMODITY_MAP: [RegExp, string][] = [
  [/\bbell pepper/i, 'Bell Pepper'],
  [/\bsweet potato/i, 'Sweet Potato'],
  [/\bbok choy/i, 'Bok Choy'],
  [/\bgreen bean/i, 'Green Bean'],
  [/\bbrussels sprout/i, 'Brussels Sprout'],
  [/\bpassion fruit/i, 'Passion Fruit'],
  [/\bdragonfruit|dragon fruit/i, 'Dragon Fruit'],
  [/\bgrapefruit/i, 'Grapefruit'],
  [/\bwatermelon/i, 'Watermelon'],
  [/\bpineapple/i, 'Pineapple'],
  [/\bpomegranate/i, 'Pomegranate'],
  [/\bcantaloupe/i, 'Cantaloupe'],
  [/\bhoneydew/i, 'Honeydew'],
  [/\btangerine/i, 'Tangerine'],
  [/\bclementine/i, 'Clementine'],
  [/\bnectarine/i, 'Nectarine'],
  [/\bblueberr/i, 'Blueberry'],
  [/\bblackberr/i, 'Blackberry'],
  [/\braspberr/i, 'Raspberry'],
  [/\bstrawberr/i, 'Strawberry'],
  [/\btomatillo/i, 'Tomatillo'],
  [/\btomato|tomatoes/i, 'Tomato'],
  [/\bpersimmon/i, 'Persimmon'],
  [/\bartichoke/i, 'Artichoke'],
  [/\basparagus/i, 'Asparagus'],
  [/\bcauliflower/i, 'Cauliflower'],
  [/\bjackfruit/i, 'Jackfruit'],
  [/\bkohlrabi/i, 'Kohlrabi'],
  [/\bplantain/i, 'Plantain'],
  [/\beggplant/i, 'Eggplant'],
  [/\bzucchini/i, 'Zucchini'],
  [/\bspinach/i, 'Spinach'],
  [/\bromaine/i, 'Romaine'],
  [/\blettuce/i, 'Lettuce'],
  [/\bcabbage/i, 'Cabbage'],
  [/\bbroccoli/i, 'Broccoli'],
  [/\bcelery/i, 'Celery'],
  [/\bfennel/i, 'Fennel'],
  [/\bparsnip/i, 'Parsnip'],
  [/\bradish/i, 'Radish'],
  [/\bturnip/i, 'Turnip'],
  [/\barugula/i, 'Arugula'],
  [/\bmushroom/i, 'Mushroom'],
  [/\bcorn/i, 'Corn'],
  [/\bcucumber/i, 'Cucumber'],
  [/\bsquash/i, 'Squash'],
  [/\bpumpkin/i, 'Pumpkin'],
  [/\bapricot/i, 'Apricot'],
  [/\bcherry|cherries/i, 'Cherry'],
  [/\bplum/i, 'Plum'],
  [/\bpeach/i, 'Peach'],
  [/\bpear/i, 'Pear'],
  [/\bapple/i, 'Apple'],
  [/\bmango/i, 'Mango'],
  [/\bpapaya/i, 'Papaya'],
  [/\bguava/i, 'Guava'],
  [/\blychee/i, 'Lychee'],
  [/\bcoconut/i, 'Coconut'],
  [/\bkiwi/i, 'Kiwi'],
  [/\bfig/i, 'Fig'],
  [/\bquince/i, 'Quince'],
  [/\bmelon/i, 'Melon'],
  [/\bgrape/i, 'Grape'],
  [/\borange/i, 'Orange'],
  [/\blemon/i, 'Lemon'],
  [/\blime/i, 'Lime'],
  [/\bbanana/i, 'Banana'],
  [/\bavocado/i, 'Avocado'],
  [/\bonion/i, 'Onion'],
  [/\bgarlic/i, 'Garlic'],
  [/\bcarrot/i, 'Carrot'],
  [/\bpotato|potatoes/i, 'Potato'],
  [/\bleek/i, 'Leek'],
  [/\bbeet/i, 'Beet'],
  [/\byam/i, 'Yam'],
  [/\bcilantro/i, 'Cilantro'],
  [/\bkale/i, 'Kale'],
  [/\bpeppers?\b/i, 'Pepper'],
]

export function detectCommodity(name: string): string | null {
  for (const [re, commodity] of COMMODITY_MAP) {
    if (re.test(name)) return commodity
  }
  return null
}
